name: ci

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  linting:
    name: Linting & Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
          architecture: x64 # optional, x64 or arm64

      - name: Create Empty .env File
        run: echo "#" > .env

      - name: Dependencies
        run: flutter pub get

      - name: Linting
        # We'll ignore info and warnings when performing this step
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Formatting
        run: dart format --set-exit-if-changed -l 200 .

      - name: Tests
        run: flutter test

      # Read the version number
      - name: Read pubspec.yaml version
        id: output-pubspec-version
        uses: NiklasLehnfeld/flutter-version-number-action@main
        with:
          file-path: pubspec.yaml

      # Read the globals.dart file
      - name: Read globals.dart version
        id: output-globals-version
        uses: juliangruber/read-file-action@v1
        with:
          path: lib/globals.dart

      # Get just the first line of the globals.dart file
      - name: Get first line of globals.dart file
        uses: jungwinter/split@v2
        id: split-globals-output
        with:
          msg: ${{ steps.output-globals-version.outputs.content }}
          separator: '\n'

      # Assert that the version has been updated in globals
      - name: Assert globals.dart has correct version
        uses: nick-fields/assert-action@v1
        with:
          expected: const String currentVersion = '${{ steps.output-pubspec-version.outputs.version-number }}';
          actual: ${{ steps.split-globals-output.outputs._0 }}
